version: '3'
services:
  ### MySQL database for Inventory
  db-inventory:
    container_name: db-inventory
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: ms_inventory
      MYSQL_USER: freddy
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306

  ### MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: freddy
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306

  ### MySQL database for Products
  db-products:
    container_name: db-products
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: ms_products
      MYSQL_USER: freddy
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306